### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinproject-iwasaki/my_bevy_game#18]
cargo-kcovはメンテナンスがされていないようなので、今回はtarpaulinとおまけとしてgrcovを使います。
https://qiita.com/w40141/items/a4ce82dbd30a44e42985

```
pre-commit:
  parallel: true
  commands:
    ...
    cargo-coverage:
      run: cargo tarpaulin --out Xml
      # 他の必要なオプションをここに追加
```
